<?xml version="1.0"?>
<package format="3">
  <name>adnav</name>
  <version>1.0.0</version>
  <description>Metapackage for adnav packages</description>

  <maintainer email="j.justin@acfr.usyd.edu.au">Jerome Justin</maintainer>

  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>adnav_driver</exec_depend>
  <exec_depend>adnav_interfaces</exec_depend>
  <exec_depend>adnav_launch</exec_depend>
    
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
